services:
  mysql:
    image: mysql:8.0
    container_name: mysql_n8n
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=n8n
      - MYSQL_USER=n8n
      - MYSQL_PASSWORD=root
    ports:
      - "3307:3306"
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - mysql_data:/var/lib/mysql

  n8n:
    image: aaoliveira/n8n-mysql:1.0
    container_name: n8n_app
    restart: always
    user: root
    depends_on:
      - mysql
    ports:
      - "5679:5678" # Mantemos a 5679 para você acessar no navegador
    env_file:
      - .env
    environment:
      - N8N_PORT=5678 # Força o n8n internamente a liberar a porta 5679
    volumes:
      - ./data:/home/node/.n8n

volumes:
  mysql_data: