services:
  mysql:
    image: mysql:8.0
    container_name: mysql_n8n # Nome padrão, caso já tenha um container com esse nome na máquina, use outro nome
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=n8n
      - MYSQL_USER=n8n
      - MYSQL_PASSWORD=root
    ports:
      - "3307:3306" # Por padrão a porta do mysql é 3306, mas na máquina local para evitar conflito com outros mysqls já instalados na máquina, usei 3307
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - mysql_data:/var/lib/mysql

  n8n:
    image: aaoliveira/n8n-mysql:1.0
    container_name: n8n_app # Nome padrão, caso já tenha um container com esse nome na máquina, use outro nome
    restart: always
    user: root
    depends_on:
      - mysql
    ports:
      - "5679:5678" # Por padrão a porta do n8n é 5678, mas na máquina local para evitar conflito com outros n8ns já instalados na máquina, usei 5679
    env_file:
      - .env
    environment:
      - N8N_PORT=5678 # Força o n8n internamente a liberar a porta 5679
    volumes:
      - ./data:/home/node/.n8n

volumes:
  mysql_data: